/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import javax.swing.JOptionPane;




public class Menus extends javax.swing.JFrame {
    private boolean Modicar;
    public Menus() {
        initComponents();
        
    }

    public void setModicar(boolean Modicar) {
        this.Modicar = Modicar;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DatosExcel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");

        DatosExcel.setAutoCreateRowSorter(true);
        DatosExcel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DatosExcel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DatosExcel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        DatosExcel.setEnabled(false);
        DatosExcel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        DatosExcel.setMinimumSize(new java.awt.Dimension(0, 0));
        DatosExcel.setPreferredSize(new java.awt.Dimension(900, 4500));
        DatosExcel.setRowHeight(150);
        DatosExcel.setRowMargin(10);
        DatosExcel.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        DatosExcel.setShowGrid(true);
        DatosExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatosExcelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DatosExcel);
        if (DatosExcel.getColumnModel().getColumnCount() > 0) {
            DatosExcel.getColumnModel().getColumn(0).setMinWidth(200);
            DatosExcel.getColumnModel().getColumn(0).setMaxWidth(200);
            DatosExcel.getColumnModel().getColumn(1).setMinWidth(200);
            DatosExcel.getColumnModel().getColumn(1).setMaxWidth(200);
            DatosExcel.getColumnModel().getColumn(2).setMinWidth(100);
            DatosExcel.getColumnModel().getColumn(2).setMaxWidth(100);
            DatosExcel.getColumnModel().getColumn(3).setMinWidth(200);
            DatosExcel.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void DatosExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatosExcelMouseClicked
        int fila=DatosExcel.rowAtPoint(evt.getPoint());
        int columna=DatosExcel.columnAtPoint(evt.getPoint());
        if(fila < DatosExcel.getRowCount() && fila >=0 && columna < DatosExcel.getColumnCount() && columna>=0){
            Object value =DatosExcel.getValueAt(fila, columna);
             if(Modicar!=false){
                 String contenido=DatosExcel.getValueAt(fila, columna).toString();
                 System.out.println(contenido);
                 String nuevocontenido=JOptionPane.showInputDialog(null, "Cambiar a:", contenido);
                 DatosExcel.setValueAt(nuevocontenido, fila, columna);
                 
             }
            
                
        }
           
            
   
    }//GEN-LAST:event_DatosExcelMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        
        
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menus().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable DatosExcel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
